server:
  port: 8010
spring:
  application:
    name: zipkin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
management:
    metrics:
      web:
        server:
         auto-time-requests: false