server:
  port: 8002
spring:
  application:
    name: zuul
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/
zuul:
  host:
    connect-timeout-millis: 2000
    socket-timeout-millis: 2000
